wandb_version: 1

epochs:
  desc: null
  value: 500
batch_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719750500
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.0
      5: 0.17.3
      8:
      - 3
      - 5
      13: windows-amd64
